server:
  port:8082
spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
          uri: https://github.com/searetseltev/calc-poc
          clone-on-start: true
          delete-untracked-branches: true